#!/usr/bin/env python3
import subprocess
import os
import sys
from termcolor import colored

OPTIONS = [
    ("--ignore", "Ignore the all file in .gitignore"),
    ("--clean", "Clean the coding-style-reports.log file"),
    ("--help", "Display this help")
]

RULES = {
    "C-G1": "Bad file header",
    "C-G2": "There should be only one line between each fonction",
    "C-G3": "Preprocessor directive must be indented",
    "C-G4": "Global Variable must be const",
    "C-G5": "#include should only contain .h files",
    "C-G6": "Line endings must be done in UNIX style",
    "C-G7": "Line should finish only end with a \"\\n\"",
    "C-G8": "Trailing space",
    "C-G9": "Constant values",
    "C-C1": "There should not be more than 3 depth (conditionnal branching)",
    "C-C3": "Forbidden goto",
    "C-A3": "Missing Line Break",
    "C-L1": "Coding content",
    "C-L2": "Bad indentation",
    "C-L3": "Misplaced spaces",
    "C-L4": "Misplaced curly bracket",
    "C-L5": "Bad variable declaration",
    "C-L6": "Bad line break",
    "C-O1": "Check useless file",
    "C-O3": "Too many fonctions in a file",
    "C-O4": "Snake case convention",
    "C-F3": "A line lenght shoud not exceed 80 columns",
    "C-F4": "A function should not exceed 20 lines",
    "C-F5": "More than 4 arguments in a function or argumentless function",
    "C-F6": "Comments inside of functions",
    "H2": "Header not protected from doucle inclusion",
    "V1": "Controlling structures and macros",
    "V3": "Pointers position",
}


def read_file(path: str):
    f = open(path, "r")
    lines = f.readlines()
    f.close()
    return lines


def compute_error(lines: list[str]) -> tuple[list, list, list]:
    majors: list[tuple[str, str, str]] = []
    minors: list[tuple[str, str, str]] = []
    infos: list[tuple[str, str, str]] = []
    for line in lines:
        parsed: list[str] = line.split(":")
        for i in range(len(parsed)):
            parsed[i] = parsed[i].strip()
        file, line, level, rule = parsed
        file_name = file.split("/")[-1].strip()
        match level:
            case "MAJOR":
                majors.append((file_name, line, rule))
            case "MINOR":
                minors.append((file_name, line, rule))
            case "INFO":
                infos.append((file_name, line, rule))
    return majors, minors, infos


def print_nb_cs_errors(errors: tuple[list, list, list]):
    majors, minors, infos = errors
    total: int = len(majors) + len(minors) + len(infos)
    print(
        colored("Coding-style errors found !",
                'red', attrs=["bold", "underline", "reverse"]))
    print(
        colored('Fix them before pushing your code !',
                'red', attrs=["bold", "underline", "reverse"]))
    print()
    print(colored(f"Total: {total}", 'magenta'), end=", ")
    print(colored(f"Majors: {len(majors)}", 'red'), end=", ")
    print(colored(f"Minors: {len(minors)}", 'yellow'), end=", ")
    print(colored(f"INFO: {len(infos)}", 'cyan'))


def print_cs_errors(errors: tuple[list, list, list]):
    majors, minors, infos = errors
    for file_name, line, rule in majors:
        print(
            colored(
                f"MAJOR: {file_name} at line:{line} {rule}: {RULES[rule]}",
                'red'
            )
        )
    for file_name, line, rule in minors:
        print(
            colored(
                f"MINOR: {file_name} at line:{line} {rule}: {RULES[rule]}",
                'yellow'
            )
        )
    for file_name, line, rule in infos:
        print(
            colored(
                f"INFO: {file_name} at line:{line} {rule}: {RULES[rule]}",
                'cyan'
            )
        )
    print()


def call_coding_style():
    process = subprocess.Popen(
        "coding-style . .", stdout=subprocess.DEVNULL, shell=True)
    process.communicate()


def ignore_file(lines: list[str]) -> list[str]:
    ignore_file = read_file(".gitignore")
    for line in ignore_file:
        if line.startswith("#"):
            ignore_file.remove(line)
        line = line.strip()
    for line in lines:
        for ignored in ignore_file:
            ignored = ignored.strip().removesuffix("\n")
            file_name = line.split(':')[0].strip(
            ).removeprefix("./")
            if file_name.endswith(ignored):
                lines.remove(line)
    return lines


def help(options):
    print("Usage: coding-style-repo [OPTIONS]")
    print("OPTIONS:")
    for opt in options:
        option, desc = opt
        print(f"\t{option}\t\t{desc}")
    exit(0)


def main():
    if "--help" in sys.argv[1:]:
        help(OPTIONS)
        exit(0)

    flags = [flag for flag, _ in OPTIONS if flag.startswith("--")]
    if len(sys.argv) > 1 and sys.argv[1] not in flags:
        print(f"Unknown option {sys.argv[1]}")
        exit(1)

    call_coding_style()
    lines = read_file("coding-style-reports.log")

    if len(sys.argv) > 1 and "--ignore" in sys.argv[1:]:
        lines = ignore_file(lines)
    if len(sys.argv) > 1 and "--clean" in sys.argv[1:]:
        os.remove("coding-style-reports.log")
    if len(lines) == 0:
        print(colored("No coding-style error found. Happy coding !", 'green'))
        exit(0)

    errors = compute_error(lines)

    print_cs_errors(errors)
    print_nb_cs_errors(errors)
    exit(1)


if __name__ == "__main__":
    main()
